version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nuxtuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nuxtpass}
      POSTGRES_DB: ${POSTGRES_DB:-nuxtdb}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
