version: '3.8'
services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: ../../tools/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./packages/backend
      dockerfile: ../../tools/docker/Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
      # Add other backend specific environment variables here
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
