name: CI Pipeline

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npx eslint .

    - name: Build project
      run: npm run build

    - name: Run tests (if test files exist)
      run: |
        if [ -d "test" ] || [ -d "tests" ] || [ -d "__tests__" ] || ls *.test.* *.spec.* 2>/dev/null | grep -q .; then
          if npm list vitest >/dev/null 2>&1; then
            npx nuxi test
          else
            echo "Test files found but vitest not installed, skipping tests"
          fi
        else
          echo "No test files found, skipping tests"
        fi
